### ISSUE TITLE
Where clause not working when used in XML

### ISSUE THREAD

**Issue by ssharma94** [Esri/mdcs-py#78]
I am trying to use the RemoveRastersFromMosaicDataset and where_clause is supported in this. But when I put the following string in the where_clause for the StdTime column which is Date format it throughs an error: **"not well-formed (invalid token): line 125, column 80"**
The have tried:
1.  <where_clause>StdTime >= timestamp '2021-01-01 00:00:00' And StdTime <= timestamp '2021-01-10 00:00:00'</where_clause>
2.  <where_clause>"StdTime >= timestamp '2021-01-01 00:00:00' And StdTime <= timestamp '2021-01-10 00:00:00'"</where_clause>
But when I use the same clause in the ArcPro using the Remove Rasters From Mosaic Dataset it work. See the screen grab below:
![image](https://user-images.githubusercontent.com/22186299/123796951-05418a80-d929-11eb-9f58-8d21bbe2cd29.png)

**Comment by bikesbade** [comment]
@ssharma94, since we are using XML for the config file, less than (<) and greater than (>), is not accepted directly so we have to use &lt; or &gt; for the less than and greater than. 

I have attached the sample clause 

sample 1:
StdTime &lt;timestamp &apos;2020-01-17 10:00:00&apos; AND StdTime &gt;timestamp &apos;2020-01-15 10:00:00&apos;

sample 2:
StdTime &lt;timestamp '2020-01-17 10:00:00' AND StdTime &gt;timestamp '2020-01-15 10:00:00'
